language: node_js
os:
  - linux
node_js:
  - "0.10"
  - "0.12"
  - "4.1"
  - "node"
after_script: npm run coverage
deploy:
  provider: npm
  email: ben@npmjs.com
  api_key: $NPM_TOKEN
  on:
    tags: true
